# What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

# Numpy Arrays Vs Python Sequences
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [5]:
import numpy as np


In [6]:
first = [ 1 , 2 ,3 , 4 ]
arr = np.array(first)

In [7]:
arr # one dimension

array([1, 2, 3, 4])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(4,)

In [10]:
arr1 = np.array([[1,2,3] , [4,5,6]])

In [11]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr1.shape # 2nd dimension

(2, 3)

In [13]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [14]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [15]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr1.dtype

dtype('int32')

In [17]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
np.arange(50,1,-1)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [19]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [24]:
5 + np.ones((3+5))

array([6., 6., 6., 6., 6., 6., 6., 6.])

In [25]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [26]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
print('Random number generation(Uniform distribution)')
np.random.rand(2,3)

Random number generation(Uniform distribution)


array([[0.99288402, 0.40107516, 0.48674157],
       [0.34588387, 0.87883201, 0.23684772]])

In [28]:
print("Random number following a Normal distribtuion with mean=0 and std=1")
print(np.random.randn(5,3))

Random number following a Normal distribtuion with mean=0 and std=1
[[ 0.90981837 -0.76449797 -0.33217136]
 [ 0.96960584 -0.47279155  0.4962563 ]
 [ 0.0143558   0.48403868  0.58820588]
 [-0.84770887 -0.23438228 -2.08138407]
 [ 0.02695909 -0.04190282  1.17054762]]


In [29]:
np.random.randint(1,100,50)

array([96, 44, 31, 79, 31, 87, 16, 75,  3,  9, 70, 55, 26, 79, 65, 38, 65,
       61, 35, 68, 20, 58, 74, 17, 73, 84, 75, 67, 70, 74, 93, 56,  9, 30,
        2, 84, 23, 45, 78, 38, 73, 55, 68, 81,  2, 67, 62, 38, 53, 14])

In [30]:
np.random.randint(1,100,(4,4))

array([[25, 77, 88, 47],
       [44, 76,  9, 92],
       [14, 38,  1, 95],
       [38, 71, 81, 74]])

In [31]:
arr = np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# slicing

In [33]:
arr[2:7:3]

array([2, 5])

In [34]:
arr[2:9:2]

array([2, 4, 6, 8])

In [35]:
arr[-1:0:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [36]:
arr[-1:0:-2]

array([10,  8,  6,  4,  2])

In [37]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [38]:
arr1

array([[88, 81, 13, 26],
       [35, 76, 25, 59],
       [48, 38,  8,  6],
       [16, 42, 53, 31],
       [99, 80, 31, 50]])

In [39]:
arr1[-3:-1,-3:-1]

array([[38,  8],
       [42, 53]])

In [40]:
arr1[:3]

array([[88, 81, 13, 26],
       [35, 76, 25, 59],
       [48, 38,  8,  6]])

In [41]:
arr1[:3,:3]

array([[88, 81, 13],
       [35, 76, 25],
       [48, 38,  8]])

# universal function

In [51]:
aar1 = np.random.randint(10,100,(3,3))
aar2 = np.random.randint(20,100,(3,3))

In [55]:
arr1

array([[88, 81, 13, 26],
       [35, 76, 25, 59],
       [48, 38,  8,  6],
       [16, 42, 53, 31],
       [99, 80, 31, 50]])

In [56]:
aar2

array([[38, 73, 74],
       [71, 49, 53],
       [93, 47, 55]])

In [57]:
aar1 + aar2

array([[ 59, 101, 122],
       [107,  73, 137],
       [140, 119,  68]])

In [58]:
aar1 * aar2

array([[ 798, 2044, 3552],
       [2556, 1176, 4452],
       [4371, 3384,  715]])

In [59]:
aar1 / aar2

array([[0.55263158, 0.38356164, 0.64864865],
       [0.50704225, 0.48979592, 1.58490566],
       [0.50537634, 1.53191489, 0.23636364]])

In [60]:
np.sqrt(aar1)

array([[4.58257569, 5.29150262, 6.92820323],
       [6.        , 4.89897949, 9.16515139],
       [6.8556546 , 8.48528137, 3.60555128]])

In [61]:
np.exp(aar2)

array([[3.18559318e+16, 5.05239363e+31, 1.37338298e+32],
       [6.83767123e+30, 1.90734657e+21, 1.04137594e+23],
       [2.45124554e+40, 2.58131289e+20, 7.69478527e+23]])

In [62]:
np.log10(aar1)

array([[1.32221929, 1.44715803, 1.68124124],
       [1.5563025 , 1.38021124, 1.92427929],
       [1.67209786, 1.8573325 , 1.11394335]])

In [63]:
arr1=np.arange(1,10)

In [64]:
arr1[2:]=1000

In [65]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])